var a=0
try
{
    if(a===0)
        throw "error found"
}
catch (e)
{
    console.log("hy")
}
finally {
    console.log("I WORKS IF WHAT ALL  HAPPENS")
}
